name = "bfp-market"
version = "<%= package.version %>"
description = "bfp market for Synthetix v3"

[setting.synthetixPackage]
defaultValue = "synthetix:<%= package.dependencies['@synthetixio/core-contracts'].replace('^', '') %>"

[import.synthetix]
source = "<%= settings.synthetixPackage %>"

[contract.OrderModule]
artifact = "OrderModule"
args = []

[contract.PerpMarketModule]
artifact = "PerpMarketModule"
args = []

# Core
[router.BigFPerpsMarketRouter]
contracts = [
  "PerpMarketModule",
  "OrderModule"
]
depends = [
  "import.synthetix",
  "contract.PerpMarketModule",
  "contract.OrderModule"
]
