name = "bfp-market"
version = "<%= package.version %>"
description = "bfp market for Synthetix v3"

# TODO: Replace burn address with a real market owner once ready.
[setting.owner]
description = "bfp market owner"
defaultValue = "0x0000000000000000000000000000000000000000"

# TODO: Configurable to depending on chain.
#
# @see: https://docs.pyth.network/documentation/pythnet-price-feeds/evm
[setting.pyth]
description = "pyth evm contract address"
defaultValue = "0xff1a0f4744e8582DF1aE09D5611b887B6a12925C"

[setting.synthetixPackage]
defaultValue = "synthetix:<%= package.dependencies['@synthetixio/core-contracts'].replace('^', '') %>"

# --- External Imports --- #

[import.synthetix]
source = "<%= settings.synthetixPackage %>"

# --- Market Contracts --- #

[contract.OrderModule]
artifact = "OrderModule"
args = []

[contract.LiquidationModule]
artifact = "LiquidationModule"
args = []

[contract.PerpMarketFactoryModule]
artifact = "PerpMarketFactoryModule"
args = []

[contract.PerpConfigurationModule]
artifact = "PerpConfigurationModule"
args = []

[contract.PerpAccountModule]
artifact = "PerpAccountModule"
args = []

[contract.PerpCollateralModule]
artifact = "PerpCollateralModule"
args = []

[contract.CoreModule]
artifact = "contracts/modules/CoreModule.sol:CoreModule"
args = []

# --- Market Proxy Contract --- #

[contract.InitialPerpMarketProxy]
artifact = "contracts/Proxy.sol:Proxy"
args = ["<%= contracts.CoreModule.address %>", "<%= settings.owner %>"]
abiOf = ["CoreModule"]
# What is salt?
#
# salt - The salt is a string which, when changed, will result in a new contract deployment.
# @see: https://usecannon.com/docs/technical-reference
salt = "<%= settings.salt %>"
depends = [
  "import.synthetix",
  "contract.CoreModule"
]

# --- Core Router --- #

[router.Router]
contracts = [
  "synthetix.AccountModule",
  "synthetix.AssociatedSystemsModule",
  "CoreModule",
  "PerpMarketFactoryModule",
  "PerpConfigurationModule",
  "PerpAccountModule",
  "PerpCollateralModule",
  "OrderModule",
  "LiquidationModule"
]
depends = [
  "import.synthetix",
  "contract.CoreModule",
  "contract.PerpMarketFactoryModule",
  "contract.PerpConfigurationModule",
  "contract.PerpAccountModule",
  "contract.PerpCollateralModule",
  "contract.OrderModule",
  "contract.LiquidationModule"
]

# --- Post Deployment --- #

[invoke.upgradeProxy]
target = ["InitialPerpMarketProxy"]
fromCall.func = "owner"
func = "upgradeTo"
args = ["<%= contracts.Router.address %>"]
# Referencing Factory-deployed Contracts
#
# @see: https://usecannon.com/docs/technical-reference/
factory.PerpMarketProxy.abiOf = ["Router"]
factory.PerpMarketProxy.event = "Upgraded"
factory.PerpMarketProxy.arg = 0
depends = ["contract.InitialPerpMarketProxy", "router.Router"]

[invoke.setSynthetix]
target = ["PerpMarketProxy"]
fromCall.func = "owner"
func = "setSynthetix"
args = [
  "<%= imports.synthetix.contracts.CoreProxy.address %>",
]
depends = ["invoke.upgradeProxy"]

[invoke.setPyth]
target = ["PerpMarketProxy"]
fromCall.func = "owner"
func = "setPyth"
args = [
  "<%= settings.pyth %>",
]
depends = ["invoke.upgradeProxy"]
